@baseUrl = http://localhost:4000/api/movie

### list
GET  {{baseUrl}}/
content-type: application/json


### show
GET  {{baseUrl}}/3
content-type: application/json


### store
POST  {{baseUrl}}/store
content-type: application/json

{
    "name": "111z",
    "country": "2",
    "actors": [{ "id": 1}],
    "categories": [{ "id": 1}]
}

### update
PUT  {{baseUrl}}/3/update
content-type: application/json

{
    "name": "111z",
    "country": "2222",
    "actors": [{ "id": 2}],
    "categories": [{ "id": 1}]
}

### destroy
DELETE   {{baseUrl}}/1/destroy
content-type: application/json

### destroy
GET   {{baseUrl}}/1/restore
content-type: application/json

